### PR TITLE
Add `ink-tab` to compatible components

### PR DESCRIPTION
**Pull request by jdeniau**
and remove incompatible components from list

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Nice component! Although you shouldn't use `<div>`, they are used internally only, use `<Box>` instead :)

> and remove incompatible components from list

Please revert this, this is already fixed it in `next` branch.

**Comment by jdeniau** [comment]
@vadimdemedes Replaced `div` by `Box` and reverted the last commit

**Comment by vadimdemedes** [comment]
Oops, PR got auto-closed, because I deleted `next` branch.

**Comment by vadimdemedes** [comment]
I added it to readme myself ;)

**Comment by jdeniau** [comment]
👌

Le mar. 5 mars 2019 à 07:25, Vadim Demedes <notifications@github.com> a
écrit :

**Pull request closed without merging**
