### PR TITLE
Add related Ink user

### PR DESCRIPTION
**Pull request by LitoMore**
### Changes

- Add my use case (An Ink app with TypeScript React)
- Fix Sindre's link

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think you could put more effort into the readme. The point is to show off Ink.

**Comment by LitoMore** [comment]
No problem. I use currently readme for my GitHub profile page. Let me separate them like yours.

**Comment by LitoMore** [comment]
@sindresorhus Updated.

**Comment by sindresorhus** [comment]
I decided to remove my CLI instead. I don't think personal tiny CLIs are interesting enough to keep in the readme.

**Comment by LitoMore** [comment]
No problem. It's OK! ✌️

**Pull request closed without merging**
