### PR TITLE
Adds support for ansi and ansi256

### PR DESCRIPTION
**Pull request by schweller**
Hi!

I'm working on a CLI and currently in need of support for `ansi` and `ansi256` from Chalk.

This PR declares four methods from Chalk's API: `ansi`, `bgAnsi`, `ansi256` and `bgAnsi256`.

### CODE REVIEW

**Comment by taras** [comment]
FYI, this was added in #264

**Comment by schweller** [comment]
Amazing @taras. Just wondering if we can merge this small change instead of waiting for #264 to be merged and released? I'm fine with it if its not an option. Thanks.

**Comment by taras** [comment]
@schweller that's a call for @vadimdemedes but it does make sense.

**Comment by vadimdemedes** [comment]
Hey @schweller, thanks for this PR! As @taras mentioned, there's currently a big PR to migrate to TypeScript and merging any PRs before that one lands would introduce merge conflicts there. Do you mind holding off for a bit until we get TS PR merged?

**Comment by schweller** [comment]
Sure. Np @vadimdemedes.

**Comment by vadimdemedes** [comment]
Merged it into master manually, thanks!

**Pull request closed without merging**
