### PR TITLE
Update React to 18

### PR DESCRIPTION
**Pull request by pepicrft**
Solves https://github.com/vadimdemedes/ink/issues/526

### Motivation

We are using Ink in a project where another dependency imports React 18 transitively and *conflicts** with the 17 version that Ink loads into the Node process.

### What

I'm opening this PR to update the version of React to 18.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Are you sure there are no other changes required to upgrade to React 18?

**Comment by pepicrft** [comment]
> Are you sure there are no other changes required to upgrade to React 18?

Not sure yet. I need to so me manual testing before. I'll let you know when the PR is ready for a review.

**Review by pepicrft — COMMENTED** [review]
@sindresorhus this one should be ready for a review. Tests are passing locally.

**Comment by pepicrft** [comment]
It'd be great if we can align the releasing of this one with [this other one](https://github.com/vadimdemedes/ink/pull/546) as a major version.

**Comment by vadimdemedes** [comment]
Thanks for this much-needed upgrade, @pepicrft! I'll take a look if anything else is needed to support React 18 in the reconciler. Last time I checked, I remember there were some additional functions in the reconciler config needed to support `startTransition` API, but I could be wrong. I'll get back to you 👍

**Comment by vadimdemedes** [comment]
> It'd be great if we can align the releasing of this one with https://github.com/vadimdemedes/ink/pull/546 as a major version.

Yep, we'll do that. I may look into some other stuff that we might want to bundle in the major release.

**Comment by pepicrft** [comment]
I'll update React as part of [this PR](https://github.com/vadimdemedes/ink/pull/546)

**Pull request closed without merging**
