### PR TITLE
Clear terminal if output is taller than viewport

### PR DESCRIPTION
**Pull request by vadimdemedes**
Fixes https://github.com/vadimdemedes/ink/issues/158.

### CODE REVIEW

**Comment by scotthovestadt** [comment]
@vadimdemedes This is something that would be especially useful for my case. Is there anything I can do to help push this forward? If there are open issues with the implementation, I can take a look and fix.

I checked out the CI complaints and it's just complaining about some minor lint rules, as far as I can tell.

**Comment by vadimdemedes** [comment]
@scotthovestadt If you could test it out in your Ink apps, that'd be a great help!

**Comment by scotthovestadt** [comment]
@vadimdemedes I (finally) applied this patch and tested it. It worked for my use-case.

**Comment by LeeCheneler** [comment]
Is there any way to turn this behaviour off? Been tearing my hair out since we realised the terminal history gets wiped when the render height is taller than the console height. We're deep into development and all use tall terminals so hadn't noticed this behaviour 😱 its not documented anywhere I've looked unless I've missed it and basically means a complete rewrite of our console apps rendering layer 😭

**Pull request merged**
