### PR TITLE
Add TypeScript setup guide

### PR DESCRIPTION
**Pull request by LitoMore**
BTW, I think TypeScript can be used as the preferred option for creating apps in the future.

I also created a PR https://github.com/vadimdemedes/create-ink-app/pull/5 for creating TypeScript Ink app  `create-ink-app`.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
@sindresorhus Do you think we need something like this? My thinking is because Ink doesn't require any special treatment to work with TypeScript, we don't need a guide for it. Normally libraries don't include guides like this, because it looks more like an intro to TypeScript itself, which in my opinion doesn't belong to Ink or other projects' readme.

**Comment by LitoMore** [comment]
I think it's useful for some TypeScript beginners.

**Comment by sindresorhus** [comment]
Yeah, I don't see the need for this either. Every single project shouldn't have to document how to use TypeScript. If you instead publish it as a blog post with some more content, we could link to it.

**Comment by LitoMore** [comment]
Make sense, thanks.

**Pull request closed without merging**
