### PR TITLE
Use svg demo

### PR DESCRIPTION
**Pull request by marionebl**
* Better quality
* Smaller file: 170kb => 3.5kb

### CODE REVIEW

**Comment by marionebl** [comment]
Linting errors tripping up Travis are unrelated

**Comment by vadimdemedes** [comment]
Could you add svg to this repo instead? Great work on `svg-term-cli` by the way.

**Comment by marionebl** [comment]
Done, glad you like it!

**Comment by vadimdemedes** [comment]
Just noticed something weird, demo doesn't loop, but bounces back. If you take a look at it, tests number increases than decreases. Like a boomerang in Instagram. Is there a way to make it loop, starting at the beginning each time like a regular gif?

**Comment by marionebl** [comment]
I deliberately did the demo like this to have a "true" loop with the first and last frame showing **0**.
Can change this, no problem.

**Comment by marionebl** [comment]
@vadimdemedes Should I change it to a "linear" loop?

**Comment by vadimdemedes** [comment]
Yep, that could be cool.

**Comment by marionebl** [comment]
Updated the demo. I also added the used demo script and command to generate a new version.

**Comment by vadimdemedes** [comment]
Thank you, looking great!

**Pull request merged**
