### PR TITLE
Renderer respects that node doesn't have to have child nodes.

### PR DESCRIPTION
**Pull request by tomasbonco**
I was having an issue with Text nodes not having `childNodes`.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Interesting, would you be able to share the code that triggers this bug?

**Comment by zkat** [comment]
@vadimdemedes https://github.com/vadimdemedes/ink/issues/115#issuecomment-464829096

**Comment by zkat** [comment]
The error seems to happen if you try to render an empty string when using `{''}` -- so `<Text>{''}</Text>` will totes repro this.

**Comment by vadimdemedes** [comment]
Hey @tomasbonco, thanks for PR! I've merged your changes manually, because I've reorganized files a bit and merge conflict was quite big.

**Comment by tomasbonco** [comment]
Guys, thanks for resolving this without me. I was really busy and didn't had time to try and reproduce the bug.

**Comment by vadimdemedes** [comment]
No worries at all, thanks for submitting original PR!

**Pull request closed without merging**
