### PR TITLE
Mention TypeScript version requirement

### PR DESCRIPTION
**Pull request by sindresorhus**
https://github.com/vadimdemedes/ink/issues/375

### CODE REVIEW

**Comment by pranshuchittora** [comment]
Hi @sindresorhus this looks awesome.
It would be great if you can mention the version of the ink which is compatible with TSv3.
`Use ink vX.Y.Z for TypeScript < v4`

**Comment by vadimdemedes** [comment]
Hm, how come Ink works with 3.9.7 in `master`?

**Comment by sindresorhus** [comment]
> Hm, how come Ink works with 3.9.7 in master?

How are you using it?

**Comment by vadimdemedes** [comment]
It's used in this repository to compile the sources. Re https://github.com/vadimdemedes/ink/issues/375, would not using `import type` fix this issue? Haven't seen this one myself before.

**Comment by sindresorhus** [comment]
> Re #375, would not using import type fix this issue? Haven't seen this one myself before.

`import type` is TS 4 only. That's what's causing this issue.

**Comment by vadimdemedes** [comment]
Huh, `import type` was introduced in 3.8 though? https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html.

**Comment by vadimdemedes** [comment]
Closing this, I removed `import type` via https://github.com/vadimdemedes/ink/commit/83894963727cf40ccac2256ec346e5ff3381c918.

**Pull request closed without merging**
