### PR TITLE
Add "Remove" escape keyboard sequence as delete key

### LINKED ISSUE #363: Delete key is not recognized
On my keyboard (Linux, Microsoft Keyboard), the Delete key is not recognized by this line : 

https://github.com/vadimdemedes/ink/blob/5c9eae4c104bc5c246b5014821f09dd9f88fb364/src/hooks/use-input.ts#L151

The key sends the "Remove" escape sequence = \u001b[3~

Modifying the line to : 

delete: input === '\u007F' || input === '\u001B[3~',

Fixes the situation.

### PR DESCRIPTION
**Pull request by grimmen**
Some keyboards with separate delete key sends this sequence

Fixes #363

### CODE REVIEW

**Comment by sindresorhus** [comment]
What operating system and machine sends such a sequence?

**Comment by grimmen** [comment]
Plain up to date Ubuntu installation, Microsoft Wireless keyboard with the
delete button in a group of six buttons above the Arrow keys.  Norwegian
keyboard layout.

**Comment by vadimdemedes** [comment]
@grimmen Could you send a link?

**Comment by vadimdemedes** [comment]
By "sequence" Sindre meant ANSI sequence (`\u001B[3~`), where is it documented?

**Comment by grimmen** [comment]
I primarily observed it being the sequence my keyboard generated when debugging the issue, and I found the same sequence on some random page under the label of "Remove".  Not able to find that again now, but in this documentation the sequence is mentioned together with the Delete key : 

https://en.wikipedia.org/wiki/ANSI_escape_code##:~:text=%3Cesc%3E[3~

**Comment by vadimdemedes** [comment]
Yeah, you are right, I also found it in `keypress` module at https://github.com/TooTallNate/keypress/blob/master/index.js#L314. Thanks for the PR!

**Comment by vadimdemedes** [comment]
Could you add a test to `test/hooks.tsx`, which ensures this sequence is treated as a delete key?

**Comment by vadimdemedes** [comment]
Here's an example PR that adds support for page up/down sequences - https://github.com/vadimdemedes/ink/pull/336.

**Comment by grimmen** [comment]
I've added a test.  The automated pull-request checker reports that it has issues with Node.js 10 - which does not seem related to my change.  It builds and the tests pass on my computer with node v.10.16.3

**Comment by vadimdemedes** [comment]
Thanks!

**Comment by vadimdemedes** [comment]
Released in [3.0.6](https://github.com/vadimdemedes/ink/releases/tag/v3.0.6).

**Pull request merged**
